# Project: 栈实现
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../栈基本定义运算函数.o ../转换后缀表达式函数.o main.o
LINKOBJ  = ../栈基本定义运算函数.o ../转换后缀表达式函数.o main.o
LIBS     = -L"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/lib" -L"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 栈实现.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../栈基本定义运算函数.o: ../栈基本定义运算函数.cpp
	$(CPP) -c ../栈基本定义运算函数.cpp -o ../栈基本定义运算函数.o $(CXXFLAGS)

../转换后缀表达式函数.o: ../转换后缀表达式函数.cpp
	$(CPP) -c ../转换后缀表达式函数.cpp -o ../转换后缀表达式函数.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
