# Project: 串
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o 串的基本运算.o KMP算法.o
LINKOBJ  = main.o 串的基本运算.o KMP算法.o
LIBS     = -L"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/lib" -L"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/dev-cpp_gr/dev-cpp_gr/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 串.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

串的基本运算.o: 串的基本运算.cpp
	$(CPP) -c 串的基本运算.cpp -o 串的基本运算.o $(CXXFLAGS)

KMP算法.o: KMP算法.cpp
	$(CPP) -c KMP算法.cpp -o KMP算法.o $(CXXFLAGS)
